gsheet_url = "https://docs.google.com/spreadsheets/d/1ltg-8vqE1CzQlDi6Ez0f4IUHYPa-B9tGP8Xi_BLQ0OU/edit?gid=0#gid=0"

[gsheet_credentials]
type = "service_account"
project_id = "questionnaires-487316"
private_key_id = "434312e12ee4a61c43c1096bcef4eb607581a90f"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDTNdAKE2yEjErZ
UFCC+oEKOuZAi9i+SVzPk4jLJ8sZQFc0qLtFGtFjF7EeHoiJ5B2bs9/rRqOtp4aF
nu5XXrpO+NSwuPPBvPK4AZ22oywbicUOePSz82WFWFTKXlM+SVcvvkkPodlSZ+VV
vkaql87HMzbXAqZSODsVUZCb4Lx/uWvleVgE47FyQQIzyGvokiDGfx0u72N7RJBA
nvcxH5BRXlZmV9J8JS4vB9SWgo3PLZ4piEPF4XBGrBcQ5gctJgBVETO51ZbzBz6J
MzVngr/JuDBc8OvyqS0/TMlpG17YadUNld71tT5D7INvyGGZncBjfc0LT+iHkdAu
10tUVgw/AgMBAAECggEAGkF/SjFd9SBHkbpFN/MSJYZq5y07VXRjQD6z66VXvxzb
emVbWlzaGLpyPy9Gg/XCpH9435OZd1XzCBtYv6279WNDdXCYhMYLWkqBI5onOokm
4QSyTsh8H1Z6u+l76atOVlYOWQ4iqPbXcJBF0qEqiGLad2IR8Piih6TrGCWY6TuW
nrVwJrC8WnJCCBltiACOEuGOm00wIWyabFotSuOVbxPLEj82nH5zkz1ShYI/B971
n096bONDsFVnPYU4iPERFaA0Ii8309WHVaskx7DEEDuhxPUPNLz03KV7fc7AOpkj
N8nOfeGfCconvX3Cnib4OaeVtK2Wvu8o6l9+ovMWOQKBgQD+GvObFGJgx+zWwlW4
fGu3H4254KbnSWmLMvgJMen73hdzrRa92lw5dLsXuGWWggbApH4hvZBna7xn3w5L
+TvIDUYBoE5MofguPe0srYbuGuNYuIyUXROpGHr49wNxX5k2KL3kfT+TkNt/IHBO
MrOEUYC+5QQKbyBLIDgYerJItQKBgQDUyPsbG+c/qPVaSHViJmuqbo0KSjxvy4U9
pZfLjj+4ICguW0qrP+7Zdm4dt6i/jdHiEUaJFk8xp4am5sqAJ5QO6BJH/TSmAZRy
g9G5lAIMaW2ujeYUuS5GKtSzZu5KoQY7wgbSGjAxpYx1qZL1VVTO64B0C3vOHcnK
Y9vH98hdowKBgHBcFInnWpT28mgIKIVaJvsjbbTafJLa6FuP3xOZyaAAlZgl2l96
1brmPfCALhN+TWQTmF5tBxRkFDxN6nF3tJKCJAmGC/lgyXARG/XciURyCUNq32af
PZlQ5Nd/yjrwjbvgCg+lvl4O+K/e9Snuy2hf7bD7bWz7tGjjx0ozvu/dAoGBALLn
oKj0VwQhTNjx3y/82b1cYd1q+VGNrqNcXTpaiZyH/QCs5SUDBhF1D7SQvKMB3JvU
ppeQWFmJXx9pII2LuWKnIOfCLsf8wBFgX69GkEpbQkrnJ7H42L1KObf1LRk2NgV8
ZzuzpR248VXkk5kOe9XWEBSBq0Brr0QpnZqN7Ls9AoGAXO8k5QZnRdDspZGix+dF
lNBtPUsVfUyimtwmsUcmbeYFvchxibCIDiIk0lbyBd327+MlK/OoZc+IeNYKB0mj
7R910uA5s1O5g/z9F3FyV2/WSTH+qkTH6CI3dgDv50fdBd9wYrsbNqVWy65dWA+y
0+adpr/Yu0KEiya+G4z8vJc=
-----END PRIVATE KEY-----
"""
client_email = "questionnaire-auto@questionnaires-487316.iam.gserviceaccount.com"
client_id = "118068422584704863042"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/questionnaire-auto%40questionnaires-487316.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
